
# Init yaml for HappyWhale
General:
    random_seed: 22
    
Data:
    dataset:
        data_directory: "/drives/hoyi1/users/ivyyen/CS7150_DL_FinalProject/HappyWhale_dataset_precropped/train/"

        data_name: "train.csv"        
    dataloader:
        batch_size: 32
        num_workers: 1
        
        
Aug:
    hf: 0.5
    
    affine: 0.5
    rotate: 10
    translate: 0.5
    shear: 10
    
    img_height: 32
    img_weight: 32
    
Train:
    model: "efficient-v2"
    lr: 0.01
    optimizar: "adam"
    epoch: 30
    loss: "focal loss"
    k_fold: 5
    

    
    
    
        
